<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-24T16:02:34 IST" name="Suite" finished-at="2022-03-24T16:03:44 IST" duration-ms="69283">
    <groups>
    </groups>
    <test started-at="2022-03-24T16:02:34 IST" name="Test" finished-at="2022-03-24T16:03:44 IST" duration-ms="69283">
      <class name="Securelandlogin.login">
        <test-method signature="adminlogin()[pri:0, instance:Securelandlogin.login@8f4ea7c]" started-at="2022-03-24T16:02:35 IST" name="adminlogin" finished-at="2022-03-24T16:02:45 IST" duration-ms="10103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- adminlogin -->
        <test-method signature="empLogin()[pri:1, instance:Securelandlogin.login@8f4ea7c]" started-at="2022-03-24T16:02:45 IST" name="empLogin" finished-at="2022-03-24T16:03:01 IST" duration-ms="16011" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- empLogin -->
        <test-method signature="createUser()[pri:2, instance:Securelandlogin.login@8f4ea7c]" started-at="2022-03-24T16:03:02 IST" name="createUser" finished-at="2022-03-24T16:03:29 IST" duration-ms="27096" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost/SecureUrlandz/register] but found [http://localhost/SecureUrlandz/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost/SecureUrlandz/register] but found [http://localhost/SecureUrlandz/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Securelandlogin.login.createUser(login.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method signature="createUser2()[pri:3, instance:Securelandlogin.login@8f4ea7c]" started-at="2022-03-24T16:03:29 IST" name="createUser2" finished-at="2022-03-24T16:03:43 IST" duration-ms="14474" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser2 -->
      </class> <!-- Securelandlogin.login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
